# project_path: 'C:/workspace/sc_2018_asim_inputs/soundcast'
# skim_file_path: 'C:/workspace/activitysim_inputs/skims.omx'
# supplemental_skim_file_path: 'C:/workspace/activitysim_inputs/skims.omx'
# assigmment_spec_file_path: 'R:/e2projects_two/activitysim/assignment_skims_inputs'


# Geolocated directory
input_dir = r'R:\e2projects_two\2023_base_year\2017_2019_survey'

run_root = r'L:\RTP_2022\final_runs\sc_rtp_2018_final\soundcast'

time_period_lookup: 
      "AM": "7to8" 
      "MD": "10to14" 
      "PM": "17to18" 
      "EV": "18to20" 
      "EA": "5to6"


build_skims: True
build_supplemental_skims: False
run_park_and_ride: False