################################################################
# Validation input files and output directory names
################################################################

model_dir = "C:/Workspace/sc_2018_new_daysim"
survey_dir = "R:/e2projects_two/2018_base_year/survey/daysim_format/revised/skims_attached"

# other validation dataset
p_acs_auto_ownership = "R:/e2projects_two/activitysim/estimation/2017_2019_data/validation_data/auto_ownership/bg_auto_ownership.csv"
p_maz_bg_lookup =      "R:/e2projects_two/activitysim/estimation/2017_2019_data/validation_data/auto_ownership/maz_bg_lookup.csv"

# validation output directory
p_output_dir = "outputs/validation"

################################################################
# run validation notebooks
################################################################
summary_list = ['auto_ownership_validation']

psrc_color = ["#F05A28", "#00A7A0", "#8CC63E", "#91268F","#4C4C4C"]