# Input includes set of MOVES input CSV files that will be updated with model years
input_dir = 'Y:/Air Quality/2026_2050_RTP/scenarios/2040_full_light_duty_EV/2023_MOVES_inputs_revised'
working_dir =  'Y:/Air Quality/2026_2050_RTP/scenarios/2040_full_light_duty_EV'
base_year = '2023'    # File
year_list = ['2035','2050']
description = 'RTP 2026-2050'

db_tag = '05_12_25_scenario_1'

run_create_moves_input_data = true
run_create_input_database_xml = true
run_create_mrs_files = true

vehicle_type_list = ['light']
county_list = ['King','Kitsap','Pierce','Snohomish','cnty_independent']

[county_id_dict] 
'King'= '53033'
'Kitsap'= '53035'
'Pierce'= '53053'
'Snohomish'= '53061'

[fname_dict] 
'sourceTypeAgeDistribution'= 'sourcetypeagedistribution'
'zoneMonthHour'= 'zonemonthhour'
'FuelUsageFraction' = 'FuelUsageFraction'
'roadTypeDistribution'= 'roadtypedistribution'
'sourceTypeYear'= 'sourcetypeyear'
'HPMSVtypeYear'= 'hpmsvtypeyear'
'monthVMTFraction'= 'monthvmtfraction'
'IMCoverage'= 'imcoverage'
'avgSpeedDistribution'= 'Default_avgSpeedDistribution'
'FuelSupply'= 'Default_FuelSupply'
'FuelFormulation'='Default_FuelFormulation'
'AVFT'= 'avft'
'dayVMTFraction'= 'dayVMTFraction'
'hourVMTFraction'= 'hourVMTFraction'